// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWVyXk3q6psbtLJ766aauLHW6kBKGELd4',
    appId: '1:333022048155:web:cbdff5d511af2191bd7b3e',
    messagingSenderId: '333022048155',
    projectId: 'auction-shop-a3d28',
    authDomain: 'auction-shop-a3d28.firebaseapp.com',
    storageBucket: 'auction-shop-a3d28.appspot.com',
    measurementId: 'G-9CCT8VF6YG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMlOwtbY5kELa3LgTpO6hjpSWL-tGslgQ',
    appId: '1:333022048155:android:7b5ec41604e82c6abd7b3e',
    messagingSenderId: '333022048155',
    projectId: 'auction-shop-a3d28',
    storageBucket: 'auction-shop-a3d28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr4yH_lSMlLVjzFI7cy4yFNydwHm_UuUo',
    appId: '1:333022048155:ios:47d85c510205c3a0bd7b3e',
    messagingSenderId: '333022048155',
    projectId: 'auction-shop-a3d28',
    storageBucket: 'auction-shop-a3d28.appspot.com',
    iosBundleId: 'com.example.auctionShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr4yH_lSMlLVjzFI7cy4yFNydwHm_UuUo',
    appId: '1:333022048155:ios:47d85c510205c3a0bd7b3e',
    messagingSenderId: '333022048155',
    projectId: 'auction-shop-a3d28',
    storageBucket: 'auction-shop-a3d28.appspot.com',
    iosBundleId: 'com.example.auctionShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWVyXk3q6psbtLJ766aauLHW6kBKGELd4',
    appId: '1:333022048155:web:aecc0e5feb3ce64fbd7b3e',
    messagingSenderId: '333022048155',
    projectId: 'auction-shop-a3d28',
    authDomain: 'auction-shop-a3d28.firebaseapp.com',
    storageBucket: 'auction-shop-a3d28.appspot.com',
    measurementId: 'G-P3MCYDN0F8',
  );
}
